(defun palindrome(s)
    (if (equal s nil)
        (format t "~%() ");for nil condition
        (print s)
    )
    (if (equal s (reverse s))
        (princ "is a palindrome")
        (princ "is not a palindrome")
    )
)
(palindrome '(a b c ) )
(palindrome '(m a d a m))
(palindrome '(cat dog))
(palindrome '())
(palindrome '(cat dog bird bird dog cat))